// Music Assistant 侧边栏配置
// 已翻译为中文

import type { SidebarGroup } from '@rspress/core';

export const musicAssistantSidebar: SidebarGroup[] = [
  {
    text: 'Music Assistant',
    items: [
      { text: '首页', link: '/music-assistant/index' },
      { text: '安装', link: '/music-assistant/installation' },
      { text: '首次运行', link: '/music-assistant/first-run' },
      { text: '概述', link: '/music-assistant/usage' },
      { text: '用户界面', link: '/music-assistant/ui' },
      { text: 'API', link: '/music-assistant/api' },
      { text: '获取帮助', link: '/music-assistant/support' },
      { text: 'Home Assistant 插件', link: '/music-assistant/ha-plugin' },
      { text: '音频管道', link: '/music-assistant/audiopipeline' },
      { text: '元数据提供者', link: '/music-assistant/metadata' },
      { text: '桌面伴侣应用', link: '/music-assistant/companion-app' },
      { text: '社区扩展', link: '/music-assistant/community-extensions' },
      { text: '发布周期', link: '/music-assistant/release' },
    ],
  },
  {
    text: '设置',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '个人资料设置', link: '/music-assistant/settings/profile' },
      { text: '音乐提供者设置', link: '/music-assistant/settings/music-provider-settings' },
      { text: '播放器提供者设置', link: '/music-assistant/settings/player-provider' },
      { text: '单个播放器设置', link: '/music-assistant/settings/individual-player' },
      { text: '系统设置', link: '/music-assistant/settings/core' },
      { text: '远程访问', link: '/music-assistant/settings/remote-access' },
      { text: '用户界面', link: '/music-assistant/settings/user-interface' },
      { text: '用户管理', link: '/music-assistant/settings/user-management' },
      { text: '关于', link: '/music-assistant/settings/about' },
    ],
  },
  {
    text: 'Home Assistant 集成',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '概述', link: '/music-assistant/integration/index' },
      { text: '安装', link: '/music-assistant/integration/installation' },
      { text: '公告', link: '/music-assistant/integration/announcements' },
      { text: '语音控制', link: '/music-assistant/integration/voice' },
    ],
  },
  {
    text: '音乐提供者',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '概述', link: '/music-assistant/music-providers/index' },
      { text: 'Apple Music', link: '/music-assistant/music-providers/apple-music' },
      { text: 'ARD Audiothek', link: '/music-assistant/music-providers/ard-audiothek' },
      { text: 'Audible 有声书', link: '/music-assistant/music-providers/audible' },
      { text: 'Audiobookshelf', link: '/music-assistant/music-providers/audiobookshelf' },
      { text: 'BBC Sounds', link: '/music-assistant/music-providers/bbc-sounds' },
      { text: '内置', link: '/music-assistant/music-providers/builtin' },
      { text: 'Deezer', link: '/music-assistant/music-providers/deezer' },
      { text: 'DI.fm 网络', link: '/music-assistant/music-providers/digitally-incorporated' },
      { text: 'gPodder 播客', link: '/music-assistant/music-providers/gpodder' },
      { text: 'iBroadcast', link: '/music-assistant/music-providers/ibroadcast' },
      { text: 'Internet Archive', link: '/music-assistant/music-providers/internet-archive' },
      { text: 'iTunes 播客', link: '/music-assistant/music-providers/itunes-podcast' },
      { text: 'Jellyfin', link: '/music-assistant/music-providers/jellyfin' },
      { text: '文件系统', link: '/music-assistant/music-providers/filesystem' },
      { text: 'NicoNico', link: '/music-assistant/music-providers/niconico' },
      { text: 'Nugs.net', link: '/music-assistant/music-providers/nugs' },
      { text: 'Phish.in', link: '/music-assistant/music-providers/phishin' },
      { text: 'Plex', link: '/music-assistant/music-providers/plex' },
      { text: 'Podcast Index', link: '/music-assistant/music-providers/podcast-index' },
      { text: 'Podcast RSS', link: '/music-assistant/music-providers/podcastfeed' },
      { text: 'Qobuz', link: '/music-assistant/music-providers/qobuz' },
      { text: 'Radio Browser', link: '/music-assistant/music-providers/radio-browser' },
      { text: 'Radio Paradise', link: '/music-assistant/music-providers/radio-paradise' },
      { text: 'SiriusXM', link: '/music-assistant/music-providers/siriusxm' },
      { text: 'SoundCloud', link: '/music-assistant/music-providers/soundcloud' },
      { text: 'Spotify', link: '/music-assistant/music-providers/spotify' },
      { text: 'Subsonic', link: '/music-assistant/music-providers/subsonic' },
      { text: 'Tidal', link: '/music-assistant/music-providers/tidal' },
      { text: 'TuneIn', link: '/music-assistant/music-providers/tunein' },
      { text: 'YouTube Music', link: '/music-assistant/music-providers/youtube-music' },
    ],
  },
  {
    text: '播放器提供者',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '概述', link: '/music-assistant/player-support/index' },
      { text: 'AirPlay', link: '/music-assistant/player-support/airplay' },
      { text: 'Alexa', link: '/music-assistant/player-support/alexa' },
      { text: 'Bluesound', link: '/music-assistant/player-support/bluesound' },
      { text: 'DLNA/UPnP', link: '/music-assistant/player-support/dlna' },
      { text: 'Fully Kiosk', link: '/music-assistant/player-support/fully-kiosk' },
      { text: 'Google Cast', link: '/music-assistant/player-support/google-cast' },
      { text: 'Home Assistant', link: '/music-assistant/player-support/ha' },
      { text: 'MusicCast', link: '/music-assistant/player-support/musiccast' },
      { text: 'Roku', link: '/music-assistant/player-support/roku' },
      { text: 'Sendspin', link: '/music-assistant/player-support/sendspin' },
      { text: 'Snapcast', link: '/music-assistant/player-support/snapcast' },
      { text: 'Sonos', link: '/music-assistant/player-support/sonos' },
      { text: 'Squeezelite', link: '/music-assistant/player-support/squeezelite' },
    ],
  },
  {
    text: '插件',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'AirPlay 接收器', link: '/music-assistant/plugins/airplay-receiver' },
      { text: 'LastFM 记录', link: '/music-assistant/plugins/lastfm_scrobble' },
      { text: 'Listenbrainz 记录', link: '/music-assistant/plugins/listenbrainz_scrobble' },
      { text: 'Plex Connect', link: '/music-assistant/plugins/plex-connect' },
      { text: 'Spotify Connect', link: '/music-assistant/plugins/spotify-connect' },
      { text: 'Subsonic 记录', link: '/music-assistant/plugins/subsonic_scrobble' },
      { text: 'VBAN 接收器', link: '/music-assistant/plugins/vban-receiver' },
    ],
  },
  {
    text: 'DSP 音频处理',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '参数均衡器', link: '/music-assistant/dsp/parametriceq' },
      { text: '音调控制', link: '/music-assistant/dsp/tonecontrols' },
    ],
  },
  {
    text: '常见问题',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '故障排除', link: '/music-assistant/faq/troubleshooting' },
      { text: '如何...', link: '/music-assistant/faq/how-to' },
      { text: '分组', link: '/music-assistant/faq/groups' },
      { text: '技术信息', link: '/music-assistant/faq/tech-info' },
      { text: '播放媒体', link: '/music-assistant/faq/massplaymedia' },
      { text: '播放公告', link: '/music-assistant/faq/massannounce' },
      { text: '传输队列', link: '/music-assistant/faq/masstransfer' },
      { text: '搜索', link: '/music-assistant/faq/masssearch' },
      { text: '获取库', link: '/music-assistant/faq/get_library' },
      { text: '获取队列', link: '/music-assistant/faq/get_queue' },
      { text: '流式传输', link: '/music-assistant/faq/stream-to' },
    ],
  },
  {
    text: '帮助与贡献',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '我想帮忙', link: '/music-assistant/help/index' },
      { text: '翻译', link: '/music-assistant/help/lokalise' },
    ],
  },
  {
    text: '移动设备',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '通用信息', link: '/music-assistant/mobile/index' },
    ],
  },
  {
    text: '博客',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Music Assistant 2.0', link: '/music-assistant/blog/2024/05/09/music-assistant-2' },
      { text: '下一个大热门', link: '/music-assistant/blog/2025/03/05/music-assistants-next-big-hit' },
      { text: '2.7 - 占领电波', link: '/music-assistant/blog/2025/12/17/music-assistant-2-7' },
    ],
  },
];

// Home Assistant Companion 侧边栏配置
export const companionSidebar: SidebarGroup[] = [
  {
    text: 'Companion Apps',
    items: [
      { text: '概述', link: '/companion/index' },
    ],
  },
  {
    text: '入门指南',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '入门指南', link: '/companion/getting_started/index' },
      { text: '连接安全级别', link: '/companion/getting_started/connection_security_level' },
    ],
  },
  {
    text: '核心功能',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '核心功能概述', link: '/companion/core/index' },
      { text: '操作', link: '/companion/core/actions' },
      { text: 'Android 版本', link: '/companion/core/android-flavors' },
      { text: '位置追踪', link: '/companion/core/location' },
      { text: '传感器', link: '/companion/core/sensors' },
    ],
  },
  {
    text: '通知',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '基础通知', link: '/companion/notifications/basic' },
      { text: '可操作通知', link: '/companion/notifications/actionable' },
      { text: '附件', link: '/companion/notifications/attachments' },
      { text: '动态内容', link: '/companion/notifications/dynamic-content' },
      { text: '关键通知', link: '/companion/notifications/critical' },
      { text: '通知详情', link: '/companion/notifications/details' },
      { text: '通知清除', link: '/companion/notifications/cleared' },
      { text: '通知命令', link: '/companion/notifications/commands' },
      { text: '通知声音', link: '/companion/notifications/sounds' },
      { text: '本地通知', link: '/companion/notifications/local' },
      { text: '接收通知', link: '/companion/notifications/received' },
    ],
  },
  {
    text: '集成',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '集成概述', link: '/companion/integrations/index' },
      { text: 'Android 设备控制', link: '/companion/integrations/android-device-controls' },
      { text: 'Android 主屏幕启动器', link: '/companion/integrations/android-home-app-launcher' },
      { text: 'Android 快速设置', link: '/companion/integrations/android-quick-settings' },
      { text: 'Android 快捷方式', link: '/companion/integrations/android-shortcuts' },
      { text: 'Android WebView', link: '/companion/integrations/android-webview' },
      { text: 'Android Widgets', link: '/companion/integrations/android-widgets' },
      { text: '应用事件', link: '/companion/integrations/app-events' },
      { text: '手势', link: '/companion/integrations/gestures' },
      { text: '触觉反馈', link: '/companion/integrations/haptics' },
      { text: 'iOS Widgets', link: '/companion/integrations/iOS-widgets' },
      { text: '分享', link: '/companion/integrations/sharing' },
      { text: 'Siri 快捷指令', link: '/companion/integrations/siri-shortcuts' },
      { text: '主题', link: '/companion/integrations/theming' },
      { text: '通用链接', link: '/companion/integrations/universal-links' },
      { text: 'URL 处理器', link: '/companion/integrations/url-handler' },
      { text: 'X-Callback-URL', link: '/companion/integrations/x-callback-url' },
    ],
  },
  {
    text: 'Apple Watch',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Apple Watch', link: '/companion/apple-watch/index' },
      { text: 'Watch 操作', link: '/companion/apple-watch/actions' },
      { text: '表盘复杂功能', link: '/companion/apple-watch/complications' },
    ],
  },
  {
    text: 'Wear OS',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Wear OS', link: '/companion/wear-os/index' },
      { text: 'Wear OS 传感器', link: '/companion/wear-os/sensors' },
    ],
  },
  {
    text: 'Android Auto',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Android Auto', link: '/companion/android-auto/index' },
    ],
  },
  {
    text: 'CarPlay',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'CarPlay', link: '/companion/carplay/index' },
    ],
  },
  {
    text: 'Meta Quest',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Meta Quest', link: '/companion/meta-quest/index' },
    ],
  },
  {
    text: '故障排除',
    collapsible: true,
    collapsed: true,
    items: [
      { text: '设置问题', link: '/companion/troubleshooting/setup' },
      { text: '错误信息', link: '/companion/troubleshooting/errors' },
      { text: '网络问题', link: '/companion/troubleshooting/networking' },
      { text: '集成问题', link: '/companion/troubleshooting/integrations' },
      { text: 'Beta 版本清理', link: '/companion/troubleshooting/beta-cleaning' },
      { text: '更多帮助', link: '/companion/troubleshooting/more-help' },
    ],
  },
  {
    text: '截图展示',
    collapsible: true,
    collapsed: true,
    items: [
      { text: 'Android 截图展示', link: '/companion/gallery/index' },
    ],
  },
];